spring:
  profiles: es1
  application:
    name: es

server:
  port: 8761


eureka:
  instance:
    prefer-ip-address: false
    hostname: es1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://es2:8762/eureka/

---

spring:
  profiles: es2
  application:
    name: es

server:
  port:  8762

eureka:
  instance:
    prefer-ip-address: false
    hostname: es2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://es1:8761/eureka/
