spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://s1:8761/eureka/,http://s2:8762/eureka/

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug