#spring:
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1
#server:
#  port: 6001
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://s1:8761/eureka/,http://s2:8762/eureka/
#
#feign:
#  hystrix:
#    enabled: true
#    user-service:
#      default:
#        execution:
#          isolation:
#            thread:
#              timeoutInMilliseconds:  3000000
#              requestVolumeThreshold: 3
#              errorThresholdPercentage: 100
#  metrics:
#    enabled: true
#
#env: ${spring.active.profiles:development2}
#
#admin:
#  name: zhirong2
#
#management:
#  server:
#    servlet:
#      context-path: /
#  endpoints:
#    web:
#      exposure:
#        include: '*'
